# .github/workflows/reusable-action.yml
name: Reusable Action Workflow

on:
  workflow_call:
    inputs:
      component-name:
        description: 'Component name'
        required: true
        type: string
      java-version:
        description: 'Java version'
        required: false
        type: string
        default: '11'

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build with Maven
        run: |
          echo "Building with Java version: ${{ inputs.java-version }}"
          sleep 10
